name: Test and Build Chrome & Firefox Extensions

on:
  push:
    branches: ["main"]
  # Triggers the workflow pull request events but only for the "main" branch
  merge_group:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.5.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Chrome
        run: pnpm build:chrome

      - name: Build Firefox
        run: pnpm build:firefox
